In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Coffee.csv")

How many rows and columns are present in the dataset?

In [6]:
df.shape

(520, 8)

What are the names of all columns in the dataset?

In [11]:
df.columns.tolist()

['Unnamed: 0',
 'Year',
 'Country',
 'Domestic Consumption',
 'Exports',
 'Import Price',
 'Export Price',
 'Total Production']

What is the data type of each column?

In [12]:
df.dtypes

Unnamed: 0                int64
Year                      int64
Country                  object
Domestic Consumption    float64
Exports                 float64
Import Price            float64
Export Price            float64
Total Production        float64
dtype: object

Display the first 5 rows of the dataset.

In [13]:
df.head()

,Unnamed: 0,Year,Country,Domestic Consumption,Exports,Import Price,Export Price,Total Production
0,0,2015,Argentina,13051.0,14887.0,2.6,2.7,26614.0
1,1,2015,Argentina,13131.0,15055.0,2.6,3.0,27019.0
2,2,2015,Argentina,13305.0,15075.0,2.7,NaN,27232.0
3,3,2015,Brazil,21070.0,36806.0,1.9,1.9,54721.0
4,4,2015,Canada,18063.0,21734.0,3.9,4.0,38987.0

Display the last 5 rows of the dataset.

In [14]:
df.tail()

,Unnamed: 0,Year,Country,Domestic Consumption,Exports,Import Price,Export Price,Total Production
515,515,2023,USA,28629.0,0.0,5.3,0.0,0.0
516,516,2023,USA,28875.0,0.0,5.2,0.0,0.0
517,517,2023,Vietnam,NaN,34342.0,2.9,3.2,52222.0
518,518,2023,Vietnam,18557.0,34695.0,3.2,2.9,52867.0
519,519,2023,Vietnam,18615.0,34840.0,3.0,NaN,52639.0

Which columns contain missing values?

In [16]:
df.isnull().sum()
df.columns[df.isnull().any()]

Index(['Domestic Consumption', 'Exports', 'Import Price', 'Export Price',
       'Total Production'],
      dtype='object')

How many unique countries are present in the dataset?

In [17]:
df["Country"].nunique()

20

How many records are available for each year?

In [18]:
df["Year"].value_counts().sort_index()

Year
2015    73
2016    58
2017    59
2018    44
2019    57
2020    58
2021    61
2022    56
2023    54
Name: count, dtype: int64

How many records are available for each country?

In [19]:
df["Country"].value_counts()

Country
France          31
Argentina       30
Colombia        30
Chile           29
South Africa    29
Germany         28
Mexico          28
Italy           28
Indonesia       27
China           26
India           26
USA             25
Vietnam         24
Canada          24
Turkey          24
Brazil          23
Ethiopia        23
Kenya           23
Thailand        22
Peru            20
Name: count, dtype: int64

Find the minimum, maximum, and average of total production.

In [20]:
df["Total Production"].agg(["min", "max", "mean"])

min          0.000000
max     264565.000000
mean     46466.726721
Name: Total Production, dtype: float64

Which country has the highest total production in a single record?

In [21]:
df.loc[df["Total Production"].idxmax()]

Unnamed: 0                   480
Year                        2023
Country                    China
Domestic Consumption    159839.0
Exports                 108888.0
Import Price                 3.9
Export Price                 3.8
Total Production        264565.0
Name: 480, dtype: object

Are there any rows where total production is missing or zero?

In [22]:
df[(df["Total Production"].isnull()) | (df["Total Production"] == 0)]

,Unnamed: 0,Year,Country,Domestic Consumption,Exports,Import Price,Export Price,Total Production
14,14,2015,China,119776.0,85031.0,3.0,3.5,NaN
27,27,2015,Germany,8514.0,11030.0,3.2,3.5,0.0
28,28,2015,Germany,8514.0,11030.0,3.2,3.5,0.0
29,29,2015,Germany,8887.0,11273.0,3.4,3.6,0.0
30,30,2015,Germany,8396.0,10988.0,3.0,3.7,0.0
...,...,...,...,...,...,...,...,...
512,512,2023,USA,28601.0,0.0,5.5,0.0,0.0
513,513,2023,USA,28632.0,0.0,5.1,0.0,0.0
514,514,2023,USA,29342.0,0.0,5.5,0.0,0.0
515,515,2023,USA,28629.0,0.0,5.3,0.0,0.0
516,516,2023,USA,28875.0,0.0,5.2,0.0,0.0

What is the average import price across all records?

In [23]:
df["Import Price"].mean()

np.float64(3.1564777327935225)

What is the total coffee production for each year?

In [24]:
df.groupby("Year")["Total Production"].sum()

Year
2015    2551154.0
2016    2163533.0
2017    2438153.0
2018    1793354.0
2019    2593378.0
2020    2756933.0
2021    2867085.0
2022    2681517.0
2023    3109456.0
Name: Total Production, dtype: float64

Which are the top 5 countries based on total production?

In [25]:
df.groupby("Country")["Total Production"].sum().sort_values(ascending=False).head(5)

Country
China        5682192.0
India        1902283.0
Mexico       1838210.0
France       1837554.0
Indonesia    1582361.0
Name: Total Production, dtype: float64

Which country has the highest average export price?

In [26]:
df.groupby("Country")["Export Price"].mean().sort_values(ascending=False).head(1)

Country
Canada    4.338095
Name: Export Price, dtype: float64

Does domestic consumption exceed total production for any country?

In [30]:
len(df[df["Domestic Consumption"] > df["Total Production"]]) > 0

True

Which country shows the highest growth in total production over the years?

In [32]:
df_sorted = df.sort_values("Year")
growth = df_sorted.groupby("Country")["Total Production"].agg(lambda x: x.iloc[-1] - x.iloc[0])
growth.sort_values(ascending=False)

Country
China           63976.0
India           18371.0
Mexico          13790.0
Brazil          11834.0
Indonesia       10852.0
France          10655.0
Vietnam         10535.0
Italy            8672.0
Thailand         8619.0
Canada           7037.0
Turkey           6600.0
Argentina        5494.0
South Africa     5157.0
Kenya            3679.0
Colombia         3180.0
Chile            3128.0
Ethiopia         3050.0
Peru             2759.0
Germany             0.0
USA                 0.0
Name: Total Production, dtype: float64

Is there any relationship between export price and total production?

In [33]:
df["Export Price"].corr(df["Total Production"])

np.float64(0.3442034661421095)

Write 4–5 lines summarizing key insights from the EDA.

After running everything we got to know --   
Production trend over years  
Dominant producing country  
Correlation strength